version: '3.8'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - db_data:/data/db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"


volumes:
  db_data: {}